---
# Database credentials
db_password: "{{ vault_db_password }}"
db_user: "{{ vault_db_user }}"
db_name: "{{ vault_db_name }}"
postgres_admin_password: "{{ vault_postgres_admin_password }}"

# Application settings
app_directory: "/opt/flask-app"
app_port: 5000
app_docker_image: "kirill4goodmopsa/flask-app"

# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_ssl_cert_path: "/etc/nginx/ssl/server.crt"
nginx_ssl_key_path: "/etc/nginx/ssl/server.key"

# Logging settings
log_directory: "/var/log/app"
log_retention_days: 7
