---
- name: Pull Flask application image from Docker Hub
  community.docker.docker_image:
    name: "{{ app_docker_image | default('kirill4goodmopsa/flask-app') }}" # app_docker_tag?
    source: pull
    force_source: true

- name: Create application directory for data
  file:
    path: "{{ app_directory }}"
    state: directory
    mode: '0755'

- name: Run Flask application container
  community.docker.docker_container:
    name: flask-app
    image: "{{ app_docker_image | default('kirill4goodmopsa/flask-app') }}:{{ app_docker_tag | default('latest') }}"
    state: started
    restart_policy: always
    env:
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "{{ db_name }}"
    ports:
      - "{{ app_port }}:5000"
    networks:
      - name: app_network
  notify: restart application

- name: Wait for Flask application to be ready
  wait_for:
    host: localhost
    port: "{{ app_port }}"
    delay: 3
    timeout: 120
