---

devops_user: "devops"
devops_user_shell: "/bin/bash"
devops_user_groups: []


firewall_allowed_ports:
  - { port: 22, proto: tcp }
  - { port: 80, proto: tcp }
  - { port: 443, proto: tcp }
  - { port: 53, proto: udp }


system_packages:
  - vim
  - git
  - htop
  - curl
  - wget


scripts_dir: "/opt/scripts"
backup_cron_hour: "2"
backup_cron_minute: "0"
healthcheck_cron_minute: "*/10"
